name: Release

on:
  release:
    types: [created]

jobs:
  linux-releases-matrix:
    name: Release Matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [ linux ]
        goarch: ["386", amd64]

    steps:
      - uses: actions/checkout@v2

      - name: Set ACTIONS_ALLOW_UNSECURE_COMMANDS env
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV
      - name: Set APP_VERSION env
        run: echo ::set-env name=APP_VERSION::$(echo ${GITHUB_REF} | rev | cut -d'/' -f 1 | rev )
      - name: Set BUILD_TIME env
        run: echo ::set-env name=BUILD_TIME::$(date)
      - name: Environment Printer
        uses: managedkaos/print-env@v1.0

      - uses: wangyoucao577/go-release-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          extra_files: config.yml.sample README.md
          build_flags: -v
          ldflags: -X 'github.com/makubex2010/flowerss-bot/config.commit=${{ github.sha }}' -X 'github.com/makubex2010/flowerss-bot/config.date=${{ env.BUILD_TIME }}' -X 'github.com/makubex2010/flowerss-bot/config.version=${{ env.APP_VERSION }}'
